### ISSUE TITLE
Login view integration

### ISSUE THREAD

**Issue by palexs** [MacKentoch/reactNativeReduxFastStarter#1]
Hi, Erwan,

Thanks for this project! 

What would be the right approach to add Login view, so that after successful login a navigation to Home view with side menu will take place?

**Comment by MacKentoch** [comment]
Hi @palexs,

Thank you, glad it helps.

It depends your needs but as far as I understand:
- you need a `login view` that **prevents showing all app** `like a first launch view` until user is **logged or registered**

There is a super easy way I used for example for a first launch view (_so the difference in my case is it does appears once = I have a flag in a persistant stored to tell me user already launched the app at least once_).

in `/ReactNativeApp/ios/container/app/App.js`:

``` javascript

render() {
    StatusBar.setBarStyle('light-content', true);
    const DEFAULT_ROUTE = { id: 1, refView: 'HomeView' };
    //////////////////////////////////////////////////
    // check a flag (props or state or persistant: it depends your needs, here this.props. userIsLogged)
    const { userIsLogged } = this.props;
    if (!userIsLogged) {
     // will only render your login view until the flag userIsLogged is true (set it true in the login view when user is logged)
     return (<YOUR_LOGIN_VIEW />);
    }
   //////////////////////////////////////////////////

   // your app will render only when user is logged
   // you can have sidemenu or anything = you have no limit
   // <YOUR _LOGIN_VIEW /> can also be used in regular routes if you need
    return (
      <SideMenu
        menu={<SideMenuContent
                backGndColor="#ECECEC"
                navigate={(route)=>this.navigate(route)}
              />}
        isOpen={this.state.sideMenuOpened}
        onChange={(isOpened) => this.updateSideMenuState(isOpened)}
        bounceBackOnOverdraw={false}
        openMenuOffset={SCREEN_WIDTH * 0.8}
        >
        <Navigator
          ref="navigator"
          initialRoute={ DEFAULT_ROUTE }
          sceneStyle={ styles.navigator }
          renderScene={(route, navigator)=>this.renderScene(route, navigator)}
          configureScene={()=>Navigator.SceneConfigs.FadeAndroid}
          navigationBar={
            <Navigator.NavigationBar
              routeMapper={this.renderRouteMapper()}
              style={styles.navBar}
            />
          }
        />
      </SideMenu>
    );

}

```

There is more complicated way: 
- using a parent navigator over App (_App will no more be the root if you prefer_). But if you just need a single view (= a login view) it may not be worth the effort (code and maintenance).
- you can also change default root view depending user is logged
  - but if you need to hide navigationBar and sidemenu it implies lot more code

**Comment by palexs** [comment]
Thank you for a prompt reply! Ok, I guess I don't even have to use navigator to navigate from Login view to Home view, as `const { userIsLogged } = this.props;` will trigger re-rendering whenever userIsLogged value is changed.

I appreciate your help! ;)

**Comment by MacKentoch** [comment]
You are welcome, thank you

**Comment by dfleider** [comment]
Sorry if this is too easy but how can I change the value of userIsLogged in my login view?. I don't know how to use very well the props and state properties

**Comment by MacKentoch** [comment]
React Native is React so this could be just a matter of props and callback as usual React:

``` javascript
    //////////////////////////////////////////////////
    // check a flag (props or state or persistant: it depends your needs, here this.props. userIsLogged)
    const { userIsLogged } = this.props;
    if (!userIsLogged) {
     // will only render your login view until the flag userIsLogged is true (set it true in the login view when user is logged)
     return (
       <YOUR_LOGIN_VIEW 
           userIsLogged={userIsLogged}
           userIsLoggedChanged={(newValue)=>this.handleUserIsloggedChanged(newValue)}
       />
     );
    }
   //////////////////////////////////////////////////

```

`this.handleUserIsloggedChanged` is a callback where your login view should send by instance the next value so that app can update its state.

**Comment by dfleider** [comment]
Sorry again but, how do I send by instance the newValue? I'm trying with this.handleUserIsloggedChanged(true), but I really have no idea

**Comment by MacKentoch** [comment]
Simple React.

If you are new to React Native and React I suggest you have a try with [React tutorial to understand basic concepts](https://facebook.github.io/react/docs/tutorial.html). 
React or React Native is the fastest learning and comprehensive JS library. 
Within few concepts only (_it takes only few hours maximum to understand_) you have the most powerful JS library in your hands.

``` javascript
/// in your "YOUR_LOGIN_VIEW component"

// somewhere in an event or anything else:
const newValue = VALUE_FROM_YOUR_COMPONENT_LOGIC;
this.props.userIsLoggedChanged(newValue)
```

**Comment by dfleider** [comment]
Thanks!!! I finally managed how to solve this. 
I have one question. If I want to put inside the side bar a button that allows the user to log-out. How can I do this?

I imagine is something related with transfering the navigator to the Login view again

Thanks!
